version: '3'
services:
   web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    volumes:
      - /app/node_modules 
      - .:/app:z
   tests:
    build: 
     context: .
     dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app:z
    command: ["npm", "run", "test"]  
